### PR TITLE
fix: correctly deserialize Option with tagged type

### LINKED ISSUE #76: [Bug]: `Option<Required<T, TAG>>`  fails to deserialize
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

On deserializing an Option containing a tag, `Semantic(None, "required tag not found")'` is encountered.

```rust
#[test]
fn option() {
    let  opt = Some(Required::<u64, 0xff>(2u32.into()));

    let mut bytes = Vec::new();
    ciborium::ser::into_writer(&opt, &mut bytes).unwrap();

    // 'called `Result::unwrap()` on an `Err` value: Semantic(None, "required tag not found")',
    let output = ciborium::de::from_reader(&bytes[..]).unwrap();
    assert_eq!(opt, output);
}
```

### Expected Behaviour

The above test should succeed. The byte representation for `Some(Required(2u32))` and `Required(2u32)` are identical, I'm not too familiar with the CBOR spec but I assume this is correct. In which case, `Some` should be implied by the presence of a tag in the encoding.

Might have something to do with the tag being discarded here https://github.com/enarx/ciborium/blob/dc9d27db71fe3e13e1e1e332fd5868b6f1acc011/ciborium/src/de/mod.rs#L525

### Environment Information

Linux SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux

rustc 1.56.1 (59eed8a2a 2021-11-01)

### Steps To Reproduce

```rust
#[test]
fn option() {
    let  opt = Some(Required::<u64, 0xff>(2u32.into()));

    let mut bytes = Vec::new();
    ciborium::ser::into_writer(&opt, &mut bytes).unwrap();

    // 'called `Result::unwrap()` on an `Err` value: Semantic(None, "required tag not found")',
    let output = ciborium::de::from_reader(&bytes[..]).unwrap();
    assert_eq!(opt, output);
}
```

### PR DESCRIPTION
**Pull request by sdbondi**
Fixes #76

### CODE REVIEW

**Comment by rjzak** [comment]
Thank you for the contribution! Seems the tests pass. Could you reword the commit message (there's a typo in "ffix"), and run `cargo fmt`?

**Comment by sdbondi** [comment]
My pleasure! Thanks for the review - done as requested.

**Comment by sdbondi** [comment]
@rjzak Thanks - When can we expect a new version to be released on crates.io?

**Comment by rjzak** [comment]
There's no timeline at the moment, but we're working on it.

**Comment by rjzak** [comment]
@sdbondi [v0.2.1](https://github.com/enarx/ciborium/releases/tag/v0.2.1) is [released](https://crates.io/crates/ciborium/0.2.1)!

**Pull request merged**
