### PR TITLE
feat(ciborium-ll): fail decoding invalid two-byte encodings of simple values

### PR DESCRIPTION
**Pull request by emonadeo**
Unblocks #137.

In context of simple values, the spec states:

> An encoder MUST NOT issue two-byte sequences that start with 0xf8 (major type 7, additional information 24) and continue with a byte less than 0x20 (32 decimal).[^1]

While ciborium adheres to this, ciborium-ll does not.
```rust
let bytes = hex::decode("f800").unwrap();
let mut decoder = Decoder::from(&bytes[..]);
decoder.pull() // Is Ok(Simple(0)), but should be Err()
```

This PR adds a check that catches it in ciborium-ll.

### RFC: Fail encoding `Simple(24)` .. `Simple(30)` and `Simple(31)`?

This PR only adds a check when decoding a.k.a. calling `decoder.pull()`.
However vice-versa encoding `Simple(24)` .. `Simple(30)` should not be possible.

- `Simple(24)` is irrepresentable
- `Simple(25)` .. `Simple(27)` are floats
- `Simple(28)` .. `Simple(30)` are reserved and [not considered well-formed](https://www.rfc-editor.org/rfc/rfc8949.html#table-3)

It's also worth noting that `Simple(31)` and `Break` are equivalent. Should both be allowed or should `Simple(31)` error in favor of `Break`?

[^1]: https://www.rfc-editor.org/rfc/rfc8949.html#section-3.3-5

### CODE REVIEW

**Review by rjzak — APPROVED** [review]
LGTM

**Comment by rjzak** [comment]
Please reword the commit to use the `-s` flag to sign, or add the `Signed-off-by: ` field to pass the DCO check.

**Comment by emonadeo** [comment]
Whoops, forgot about that. Force pushed.

**Comment by npmccallum** [comment]
@emonadeo @rjzak I don't think this patch was ready to merge. There are clearly unresolved questions in the comments in the patch.

I'm also not understanding why this patch is necessary. The spec says that an encoder must not produce those bytes. But, if I understand this patch correctly, it stops the decoder from decoding these bytes. Is that correct?

**Comment by npmccallum** [comment]
@emonadeo There is a long standing practice in codecs to be strict during encoding and liberal during decoding (so long as it doesn't create a security risk). This crate follows that methodology. This patch implements a requirement that goes above and beyond what the standard requires and goes against the methodology of this crate to be liberal during decoding.

The other problem is that `ciborium-ll` intends to implement syntactic checking but not semantic checking. That's what higher level code does. This patch adds semantic checking at the wrong layer. As I see it, `ciborium` is where semantic evaluation is performed. And we do error at that layer. Applications shouldn't generally use `ciborium-ll` unless they require a very minimal approach (i.e. embedded applications). If they do, they are responsible to validate semantic meaning since `ciborium-ll` only does syntactic evaluation.

But I want to be very clear that if there is justification to break that structure, I'm happy to be convinced.

**Comment by npmccallum** [comment]
@rjzak Let's rollback since I don't yet see justification for this approach.

**Comment by emonadeo** [comment]
> But I want to be very clear that if there is justification to break that structure, I'm happy to be convinced.

There isn't besides unittest happy.

> There is a long standing practice in codecs to be strict during encoding and liberal during decoding (so long as it doesn't create a security risk). This crate follows that methodology.

This PR definitely doesn't align with that. Reconsidering how the spec is worded it's probably intended.

+1 on rolling back. Much appreciate the feedback.

**Comment by rjzak** [comment]
> @rjzak Let's rollback since I don't yet see justification for this approach.

What's the best approach? I was thinking of a rebase and drop this commit and force push. Is there a better way?

**Comment by rjzak** [comment]
Done.

**Pull request merged**
