### PR TITLE
Fix for untyped Enum values bug

### LINKED ISSUE #5: Using untyped Enum values throws off next value on deserialisation
Consider these two structs:
 `#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum NumberEnum {
    num(u128),
    stringy(String),
    nuffing,
}`
`#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SimpleStructBackend3 {
    pub number: u16,
    pub string: String,
    pub numbenum: NumberEnum,
    pub uuid: Uuid,
}`

Initialising a `SimpleStructBackend3` with `numbenum = NumberEnum::num(42)` or `numberenum = NumberEnum::stringy(String::from("forty-two")` is fine.  Initialising it with `numbenum = NumberEnum::nuffing` causes uuid to fail to deserialise.  No problems found if `numbenum` is the **final** field in `SimpleStructBackend3`.  For some reason, choosing a untyped Enum value causes the **next** field in the struct (`uuid`, in this case) to have the mismatch `Title = Other, Major = Text`, which causes a panic.

### PR DESCRIPTION
**Pull request by MikeCamel**
Signed-off-by: MikeCamel <mike@p2ptrust.org>

Fixes #5.  May require a broader (read "better, more complete") fix.

### CODE REVIEW

**Comment by MikeCamel** [comment]
Consider this a proof that #5 was correctly describing the problem, and a possible intermediate fix.

**Comment by npmccallum** [comment]
@MikeCamel We need a test that hits this code path to ensure:
1. That this fixes a real problem.
2. That the fix works.
3. That we don't break it in the future.

**Comment by MikeCamel** [comment]
I know it's not an automated test as part of the suite, but the code attached to #5 does 1 & 2.  I've not had the chance to get my head round tests in Rust properly, and there's a trade-off between getting stuff actually working and everything else which the former is currently winning.

**Comment by MikeCamel** [comment]
And I'm not having a great day, which isn't helping.

**Comment by npmccallum** [comment]
Fixed in 8dff40c65e41d4c85e6a01806b366a649f055725.

**Pull request closed without merging**
