### PR TITLE
`ciborium::value::Value` data extraction utils (inspired by `serde_json`)

### PR DESCRIPTION
**Pull request by lmammino**
Hello,
this PR introduces some utility functions to easily extract data out of generic `Value` objects. This is inspired by the utilities you get with `serde_json` for their respective `Value` type (see https://github.com/serde-rs/json/blob/master/src/value/mod.rs#L345).

Here's an example of how this might work:

```rust
use ciborium::value::Value;

let mut value = Value::Array(
    vec![
        Value::Text(String::from("foo")),
        Value::Text(String::from("bar"))
    ]
);

value.as_array_mut().unwrap().clear();
assert_eq!(value, Value::Array(vec![]));
```

## TODO

- [x] impl `is_map`
- [x] impl `as_map`
- [x] impl `as_map_mut`
- [x] impl `is_array`
- [x] impl `as_array`
- [x] impl `as_array_mut`
- [x] impl `is_integer`
- [x] impl `as_integer`
- [x] impl `is_bytes`
- [x] impl `as_bytes`
- [x] impl `as_bytes_mut`
- [x] impl `is_float`
- [x] impl `as_float`
- [x] impl `is_text`
- [x] impl `as_text`
- [x] impl `as_text_mut`
- [x] impl `as_str`
- [x] impl `is_bool`
- [x] impl `as_bool`
- [x] impl `is_null`
- [x] impl `is_tag`
- [x] impl `as_tag`
- [x] impl `as_tag_mut`

### CODE REVIEW

**Comment by npmccallum** [comment]
@lmammino Yes! We would love to have similar parity to `serde_json`.

**Comment by lmammino** [comment]
@npmccallum, @wgwoods, @rvolosatovs this is now ready for review. 👀

**Comment by lmammino** [comment]
Hello, any chance you could have a look at this one?

if you need an example use case, I am using it here: https://github.com/lmammino/green-pass/blob/0ad9c51/src/cwt.rs#L154-L173

**Review by npmccallum — APPROVED** [review]

**Comment by lmammino** [comment]
Thanks for merging this @npmccallum! 🎉

**Pull request merged**
