### PR TITLE
New reader API that allows providing the scratch buffer.

### LINKED ISSUE #69: [Feature]: Make deserializer scratch size configurable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I end up using ciborium via the `cddl` crate, for which I am maintaining a Python wrapper: https://gitlab.com/tahoe-lafs/pycddl.

The CDDL validation code ends up being used to validate potentially large (megabytes, hundreds of megabytes) CBOR documents. Parsing the CBOR is a reasonable chunk of CPU time for CDDL validation, and CDDL validation is noticeable chunk of CPU time for handling requests in end-user application. A larger buffer size shrinks this CPU overhead quite a bit.

Two examples, parsing a CBOR-encoded bytestring:

| Parsing |  CPU instructions with 4096 buffer | CPU instructions with 65536 buffer |
|------------------------|---|---|
| 1GB bytestring  once |82M | 6.5M|
| 128KB bytestring, 10,000 times | 48M | 13M|

### Acceptance Criteria

I imagine current scratch is small for use in restricted memory contexts, and uses no allocation to support executions context with allocator. So that can't go away.

On the other hand, anything using Python would be perfectly fine with a 64KB buffer (though that shouldn't be on the stack probably).

### Suggestions for a technical implementation

Some options:

1. Make `Deserializer` public. This is a low-level option, and increases API surface.
2. Accept an optional scratch buffer argument to `from_reader`. This would be backwards incompatible.
3. New public API, `from_reader_with_buffer()`. This would be backwards compatible.

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #69

### CODE REVIEW

**Comment by itamarst** [comment]
Initial results with my more end-to-end `pycddl` benchmarks suggests switching to 64KB buffer slows things down, instead of the expected speedup, so I am now confused.

**Comment by itamarst** [comment]
Ah, I misread the benchmarks for the issue; fewer instructions, yes, but also more cycles.

**Comment by itamarst** [comment]
Give the above, it's not clear to me if this PR does anything useful, possibly should just be rejected.

**Comment by rjzak** [comment]
Tests seem stuck, closing & re-opening

**Comment by rjzak** [comment]
@itamarst I'm sorry this has taken so long. Could you update the commit message to be a conventional commit? Something like: `feat: new reader API that allows providing the scratch buffer`.

**Review by rjzak — APPROVED** [review]

**Comment by itamarst** [comment]
Thanks for merging, and sorry I didn't get back to you on above, just super busy at the moment.

**Comment by rjzak** [comment]
No worries, I understand :)

**Pull request merged**
